// Extract the game-icons.net glyphs the game uses into a small TS module.
// Icons by Lorc, Delapouite and contributors, https://game-icons.net, CC BY 3.0.
//   node scripts/icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const MAP = {
  // deeds
  converse: 'conversation', introduce: 'talk', gift: 'present', whisper: 'lips', fabricate: 'quill-ink',
  spy: 'spy', scheme: 'cloak-dagger', advance: 'hourglass', recruit: 'minions', denounce: 'banging-gavel',
  strike: 'backstab', blackmail: 'stabbed-note', petition: 'kneeling', counsel: 'lovers', guard: 'guards',
  grant: 'house-keys', abandon: 'tattered-banner', flee: 'cloaked-figure-on-horseback', escape: 'breaking-chain',
  arrest: 'manacles', question: 'suspicious', execute: 'executioner-hood', release: 'padlock-open', appoint: 'vertical-banner',
  // people and status
  king: 'throne-king', crown: 'crown', queen: 'queen-crown', lord: 'knight-banner', knight: 'black-knight-helm',
  lady: 'tiara', clergy: 'prayer-beads', servant: 'cowled', unknown: 'hooded-figure', prisoner: 'prisoner',
  dead: 'tombstone', fled: 'cloaked-figure-on-horseback', you: 'person',
  // offices
  marshal: 'crossed-swords', chancellor: 'scroll-quill', spymaster: 'all-seeing-eye', captain: 'guarded-tower', confessor: 'church',
  // traits
  ambition: 'podium-winner', cunning: 'fox-head', honor: 'scales', boldness: 'lion', greed: 'coins-pile',
  wrath: 'angry-eyes', paranoia: 'paranoia', will: 'mailed-fist', charm: 'rose', martial: 'broadsword',
  // resources and views
  gold: 'two-coins', favour: 'crowned-heart', secrets: 'secret-book', schemes: 'cloak-dagger', land: 'castle',
  time: 'hourglass', map: 'spider-web', briefing: 'scroll-unfurled', chronicle: 'open-book', people: 'family-tree',
  dossier: 'magnifying-glass', witan: 'medieval-pavilion', feast: 'meal', house: 'family-house',
  // secret kinds and tones
  regicide: 'crowned-skull', murder: 'dripping-knife', concealment: 'silenced', usurpation: 'crown-of-thorns',
  pact: 'wax-seal', theft: 'shiny-purse', betrayal: 'backstab', slander: 'snake-tongue', ruin: 'tied-scroll',
  affair: 'love-mystery', threat: 'plain-dagger', suspect: 'suspicious', motive: 'drama-masks',
  good: 'laurel-crown', bad: 'broken-heart', dire: 'tombstone', court: 'banging-gavel', secret: 'lips', neutral: 'conversation',
  love: 'hearts', hate: 'broken-heart', family: 'family-tree', lover: 'love-mystery', brother: 'two-shadows',
};

const data = JSON.parse(readFileSync('node_modules/@iconify-json/game-icons/icons.json', 'utf8'));
const out = {};
const missing = [];
for (const [key, name] of Object.entries(MAP)) {
  const icon = data.icons[name];
  if (!icon) missing.push(`${key}→${name}`);
  else out[key] = icon.body;
}
if (missing.length) {
  console.error('missing icons:', missing.join(', '));
  process.exit(1);
}
const lines = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
writeFileSync(
  'src/ui/icons/gi.ts',
  `// Generated by scripts/icons.mjs — do not edit by hand.
// Icons by Lorc, Delapouite and contributors, https://game-icons.net, licensed CC BY 3.0.
// Each entry is the inner SVG of a 512×512 icon.
export const GI = {
${lines.join('\n')}
} as const;

export type GIName = keyof typeof GI;
`,
);
console.log(`wrote ${Object.keys(out).length} icons`);
